number1 = float(input("Enter 1 number: "))
number2 = float(input("Enter 2 number: "))
number3 = float(input("Enter 3 number: "))
number4 = float(input("Enter 4 number: "))
answer = (number1 + number2) / (number3 + number4)
print("Answer = %.2f" % answer)
